image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-card-delivery.jar &

build_script:
  - chmod +x gradlew
  # запускаем тест, флаг --info позволяет выводить больше информации, флаг -Dselenide.headless=true запуск selenide
  # в headless-режиме
  - ./gradlew test --info -Dselenide.headless=true